# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map_key.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


def get_frame(img_path):
    frame_widget = QtWidgets.QWidget()
    layout = QtWidgets.QGridLayout()
    layout.setContentsMargins(0, 0, 0, 0)
    imgw = ImgWidget(img_path)
    layout.addWidget(imgw, 0, 1)  # add the widget in the second colum
    layout.setColumnStretch(0, 1)  # set stretch of first
    layout.setColumnStretch(2, 1)  # and third column
    frame_widget.setLayout(layout)
    return frame_widget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(388, 415)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 210, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.enemies_table = QtWidgets.QTableWidget(self.centralwidget)
        self.enemies_table.setGeometry(QtCore.QRect(110, 240, 171, 131))
        self.enemies_table.setAutoFillBackground(False)
        self.enemies_table.setShowGrid(True)
        self.enemies_table.setWordWrap(True)
        self.enemies_table.setCornerButtonEnabled(True)
        self.enemies_table.setRowCount(4)
        self.enemies_table.setColumnCount(2)
        self.enemies_table.setObjectName("enemies_table")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.enemies_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.enemies_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.enemies_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.enemies_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.enemies_table.setItem(3, 0, item)
        self.enemies_table.horizontalHeader().setVisible(False)
        self.enemies_table.horizontalHeader().setCascadingSectionResizes(True)
        self.enemies_table.horizontalHeader().setDefaultSectionSize(81)
        self.enemies_table.horizontalHeader().setHighlightSections(True)
        self.enemies_table.horizontalHeader().setMinimumSectionSize(27)
        self.enemies_table.verticalHeader().setVisible(False)
        self.enemies_table.verticalHeader().setCascadingSectionResizes(False)
        self.enemies_table.verticalHeader().setDefaultSectionSize(31)
        self.enemies_table.verticalHeader().setMinimumSectionSize(30)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 40, 331, 161))
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(4, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(81)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(27)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(31)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 388, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.tableWidget.setCellWidget(1, 1, get_frame("key/c1s.png"))
        self.tableWidget.setCellWidget(1, 2, get_frame("key/c1apc.png"))
        self.tableWidget.setCellWidget(1, 3, get_frame("key/c1cc.png"))
        self.tableWidget.setCellWidget(2, 1, get_frame("key/c2s.png"))
        self.tableWidget.setCellWidget(2, 2, get_frame("key/c2apc.png"))
        self.tableWidget.setCellWidget(2, 3, get_frame("key/c2cc.png"))
        self.tableWidget.setCellWidget(3, 1, get_frame("key/c3s.png"))
        self.tableWidget.setCellWidget(3, 2, get_frame("key/c3apc.png"))
        self.tableWidget.setCellWidget(3, 3, get_frame("key/c3cc.png"))
        self.tableWidget.setCellWidget(4, 1, get_frame("key/chosenS.png"))
        self.tableWidget.setCellWidget(4, 2, get_frame("key/chosenAPC.png"))

        self.enemies_table.setCellWidget(1, 1, get_frame("key/enemyS.png"))
        self.enemies_table.setCellWidget(2, 1, get_frame("key/enemyL"))
        self.enemies_table.setCellWidget(3, 1, get_frame("key/enemyLP"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle("Map Key")
        self.label.setText(_translate("MainWindow", "Our Forces:"))
        self.label_2.setText(_translate("MainWindow", "Enemies:"))
        __sortingEnabled = self.enemies_table.isSortingEnabled()
        self.enemies_table.setSortingEnabled(False)
        item = self.enemies_table.item(0, 1)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.enemies_table.item(1, 0)
        item.setText(_translate("MainWindow", "Soldier"))
        item = self.enemies_table.item(2, 0)
        item.setText(_translate("MainWindow", "Launcher"))
        item = self.enemies_table.item(3, 0)
        item.setText(_translate("MainWindow", "Lookout Point"))
        self.enemies_table.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Soldier"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "APC"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "Company Commander"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Company 1"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "Company 2"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "Company 3"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "Chosen"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)


class ImgWidget(QtWidgets.QLabel):
    def __init__(self, path, parent=None):
        super(ImgWidget, self).__init__(parent)
        pic = QtGui.QPixmap(path)
        pic = pic.scaledToWidth(12)
        self.setPixmap(pic)


def main():
    import sys
    # QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
